'use client'

import { Tag, FileText } from 'lucide-react'

interface BlogPreviewProps {
  blog: {
    title: string
    subtitle: string
    summary: string
    tags: string[]
    sections: Array<{
      title: string
      content: string
    }>
  }
}

export default function BlogPreview({ blog }: BlogPreviewProps) {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="border-b border-gray-200 pb-4">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">{blog.title}</h1>
        {blog.subtitle && (
          <p className="text-lg text-gray-600 mb-3">{blog.subtitle}</p>
        )}
        <p className="text-gray-700 leading-relaxed">{blog.summary}</p>
        
        {blog.tags.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-4">
            {blog.tags.map((tag, index) => (
              <span
                key={index}
                className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary-100 text-primary-800"
              >
                <Tag className="w-3 h-3 mr-1" />
                {tag}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Sections */}
      <div className="space-y-6">
        {blog.sections.map((section, index) => (
          <div key={index} className="border-l-4 border-primary-200 pl-4">
            <h2 className="text-lg font-semibold text-gray-900 mb-2 flex items-center">
              <FileText className="w-4 h-4 mr-2 text-primary-600" />
              {section.title}
            </h2>
            <div 
              className="text-gray-700 leading-relaxed prose prose-sm max-w-none"
              dangerouslySetInnerHTML={{ __html: section.content }}
            />
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="pt-4 border-t border-gray-200">
        <p className="text-sm text-gray-500 text-center">
          Generated by ChatURL2Blog
        </p>
      </div>
    </div>
  )
} 