'use client'

import { User, Bot, MessageSquare } from 'lucide-react'

interface TranscriptViewProps {
  transcript: Array<{
    speaker: string
    message: string
    timestamp?: string
  }>
}

export default function TranscriptView({ transcript }: TranscriptViewProps) {
  return (
    <div className="space-y-4">
      <div className="flex items-center mb-4">
        <MessageSquare className="w-5 h-5 text-primary-600 mr-2" />
        <h3 className="text-lg font-semibold text-gray-900">Conversation Transcript</h3>
      </div>
      
      <div className="space-y-4 max-h-96 overflow-y-auto">
        {transcript.map((exchange, index) => (
          <div
            key={index}
            className={`flex gap-3 ${
              exchange.speaker.toLowerCase().includes('human') || exchange.speaker.toLowerCase().includes('user')
                ? 'justify-start'
                : 'justify-end'
            }`}
          >
            <div
              className={`max-w-xs lg:max-w-md p-3 rounded-lg ${
                exchange.speaker.toLowerCase().includes('human') || exchange.speaker.toLowerCase().includes('user')
                  ? 'bg-blue-100 text-blue-900'
                  : 'bg-gray-100 text-gray-900'
              }`}
            >
              <div className="flex items-center mb-2">
                {exchange.speaker.toLowerCase().includes('human') || exchange.speaker.toLowerCase().includes('user') ? (
                  <User className="w-4 h-4 mr-2" />
                ) : (
                  <Bot className="w-4 h-4 mr-2" />
                )}
                <span className="text-sm font-medium">{exchange.speaker}</span>
                {exchange.timestamp && (
                  <span className="text-xs text-gray-500 ml-auto">{exchange.timestamp}</span>
                )}
              </div>
              <div 
                className="text-sm leading-relaxed"
                dangerouslySetInnerHTML={{ __html: exchange.message }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="pt-4 border-t border-gray-200">
        <p className="text-sm text-gray-500 text-center">
          {transcript.length} exchanges • Generated by ChatURL2Blog
        </p>
      </div>
    </div>
  )
} 